import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        String receiptString="============= Order details =============\n";
        String[] str = new String[inputs.size()];
        int sum = 0;
        int sum1 = 0;
        int half = 0;
        boolean isHalf = false;
        List<String> a = new ArrayList<>();
        for (int i = 0; i < inputs.size(); i++) {
            str[i] = inputs.get(i);
            String id = str[i].substring(0,8);
            Integer num = Integer.parseInt(str[i].substring(11));
            for(int j=0;j<itemRepository.findAll().size();j++){
                if(id.equals(itemRepository.findAll().get(j).getId()) ){
                    double price = itemRepository.findAll().get(j).getPrice();
                    String name = itemRepository.findAll().get(j).getName();
                    sum += Math.round(price * num);
                    if(salesPromotionRepository.findAll().get(1).getRelatedItems().contains(id)){
                        half += Math.round(price * num / 2);
                        a.add(name);
                        isHalf = true;
                    }
                    else {
                        half += Math.round(price * num);
                    }

                    receiptString += name+" x "+num+" = "+Math.round(price * num)+" yuan\n";
                }
            }

        }
        if(isHalf){

            if(sum>=30 && (sum - 6)<=half){
                receiptString += "-----------------------------------\n" + "Promotion used:\n";
                receiptString += "满30减6 yuan，saving 6 yuan\n";
                receiptString += "-----------------------------------\n" + "Total："+(sum-6)+" yuan\n";
            }
            else {
                receiptString += "-----------------------------------\n" + "Promotion used:\n";
                receiptString += "Half price for certain dishes (";
                for (int k=0;k<a.size();k++){
                    if(k==a.size()-1){
                        receiptString += a.get(k);
                    }
                    else {
                        receiptString += a.get(k)+"，";
                    }
                }
                receiptString += ")，saving "+(sum-half)+" yuan\n";
                receiptString += "-----------------------------------\n" + "Total："+half+" yuan\n";
            }
        }
        else if(sum>=30){
            receiptString += "-----------------------------------\n" + "Promotion used:\n";
            receiptString += "满30减6 yuan，saving 6 yuan\n";
            receiptString += "-----------------------------------\n" + "Total："+(sum-6)+" yuan\n";
        }
        else {
            receiptString += "-----------------------------------\n";
            receiptString += "Total："+sum+" yuan\n";
        }
        receiptString += "===================================";
        return receiptString;
    }
}
